[2024-09-22T10:51:21.353+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.create_dims_table manual__2024-09-22T10:51:00.300457+00:00 [queued]>
[2024-09-22T10:51:21.382+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.create_dims_table manual__2024-09-22T10:51:00.300457+00:00 [queued]>
[2024-09-22T10:51:21.383+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-22T10:51:21.410+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_dims_table> on 2024-09-22 10:51:00.300457+00:00
[2024-09-22T10:51:21.420+0000] {standard_task_runner.py:57} INFO - Started process 2330 to run task
[2024-09-22T10:51:21.426+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'create_dims_table', 'manual__2024-09-22T10:51:00.300457+00:00', '--job-id', '1117', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmp_m96id_r']
[2024-09-22T10:51:21.436+0000] {standard_task_runner.py:85} INFO - Job 1117: Subtask create_dims_table
[2024-09-22T10:51:21.555+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.create_dims_table manual__2024-09-22T10:51:00.300457+00:00 [running]> on host 1646e3dc8472
[2024-09-22T10:51:21.664+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='create_dims_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T10:51:00.300457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T10:51:00.300457+00:00'
[2024-09-22T10:51:21.667+0000] {sql.py:274} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS dim_district (
        id SERIAL PRIMARY KEY,
        district VARCHAR(20),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_metro (
        id SERIAL PRIMARY KEY,
        metro_station VARCHAR(100),
        metro_time INTEGER,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_text (
        id SERIAL PRIMARY KEY,
        description TEXT,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_seller (
        id SERIAL PRIMARY KEY,
        seller VARCHAR(50),
        seller_type VARCHAR(50),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_advt (
        id SERIAL PRIMARY KEY,
        active SMALLINT,
        url VARCHAR(255),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_building (
        id SERIAL PRIMARY KEY,
        address VARCHsAR(255),
        wall_material VARCHAR(255),
        max_floor INTEGER,
        type VARCHAR(50),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_geo (
        id SERIAL PRIMARY KEY,
        lat DECIMAL,
        lon DECIMAL,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_flat_params (
        id SERIAL PRIMARY KEY,
        floor INTEGER,
        rooms INTEGER,
        area DECIMAL,
        furniture SMALLINT,
        repair VARCHAR(50),
        kitchen_furniture SMALLINT,
        wcs INTEGER,
        washing_machine SMALLINT,
        ceil_height DECIMAL,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );
[2024-09-22T10:51:21.681+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-22T10:51:22.119+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-22T10:51:22.550+0000] {sql.py:418} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS dim_district (
        id SERIAL PRIMARY KEY,
        district VARCHAR(20),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_metro (
        id SERIAL PRIMARY KEY,
        metro_station VARCHAR(100),
        metro_time INTEGER,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_text (
        id SERIAL PRIMARY KEY,
        description TEXT,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_seller (
        id SERIAL PRIMARY KEY,
        seller VARCHAR(50),
        seller_type VARCHAR(50),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_advt (
        id SERIAL PRIMARY KEY,
        active SMALLINT,
        url VARCHAR(255),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_building (
        id SERIAL PRIMARY KEY,
        address VARCHsAR(255),
        wall_material VARCHAR(255),
        max_floor INTEGER,
        type VARCHAR(50),
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_geo (
        id SERIAL PRIMARY KEY,
        lat DECIMAL,
        lon DECIMAL,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dim_flat_params (
        id SERIAL PRIMARY KEY,
        floor INTEGER,
        rooms INTEGER,
        area DECIMAL,
        furniture SMALLINT,
        repair VARCHAR(50),
        kitchen_furniture SMALLINT,
        wcs INTEGER,
        washing_machine SMALLINT,
        ceil_height DECIMAL,
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    );, parameters: None
[2024-09-22T10:51:22.733+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "varchsar" does not exist
LINE 42:         address VARCHsAR(255),
                         ^

[2024-09-22T10:51:22.749+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=create_dims_table, execution_date=20240922T105100, start_date=20240922T105121, end_date=20240922T105122
[2024-09-22T10:51:22.771+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1117 for task create_dims_table (type "varchsar" does not exist
LINE 42:         address VARCHsAR(255),
                         ^
; 2330)
[2024-09-22T10:51:22.824+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-22T10:51:22.891+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
