[2024-09-29T08:57:17.598+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T08:56:09.532251+00:00 [queued]>
[2024-09-29T08:57:17.622+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T08:56:09.532251+00:00 [queued]>
[2024-09-29T08:57:17.625+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T08:57:17.664+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_flats> on 2024-09-29 08:56:09.532251+00:00
[2024-09-29T08:57:17.675+0000] {standard_task_runner.py:57} INFO - Started process 244 to run task
[2024-09-29T08:57:17.680+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_flats', 'manual__2024-09-29T08:56:09.532251+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpr8451ds4']
[2024-09-29T08:57:17.687+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask get_flats
[2024-09-29T08:57:17.900+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_flats manual__2024-09-29T08:56:09.532251+00:00 [running]> on host 5096eb060c49
[2024-09-29T08:57:18.148+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_flats' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T08:56:09.532251+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T08:56:09.532251+00:00'
[2024-09-29T09:00:48.490+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-14:
[2024-09-29T09:00:48.493+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T09:00:48.494+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T09:00:48.494+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T09:00:48.495+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T09:00:48.495+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T09:00:48.495+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 145, in get_flat
[2024-09-29T09:00:48.496+0000] {logging_mixin.py:151} WARNING -     flat['description'] = soup.find_all("div", {'itemprop': "description"})[0].text
[2024-09-29T09:00:48.497+0000] {logging_mixin.py:151} WARNING - IndexError: list index out of range
[2024-09-29T09:01:02.113+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-15:
[2024-09-29T09:01:02.114+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T09:01:02.114+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T09:01:02.115+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T09:01:02.115+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T09:01:02.116+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T09:01:02.116+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 145, in get_flat
[2024-09-29T09:01:02.117+0000] {logging_mixin.py:151} WARNING -     flat['description'] = soup.find_all("div", {'itemprop': "description"})[0].text
[2024-09-29T09:01:02.117+0000] {logging_mixin.py:151} WARNING - IndexError: list index out of range
[2024-09-29T09:04:57.679+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-29:
[2024-09-29T09:04:57.681+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T09:04:57.682+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T09:04:57.683+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T09:04:57.683+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T09:04:57.684+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T09:04:57.684+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 145, in get_flat
[2024-09-29T09:04:57.685+0000] {logging_mixin.py:151} WARNING -     flat['description'] = soup.find_all("div", {'itemprop': "description"})[0].text
[2024-09-29T09:04:57.685+0000] {logging_mixin.py:151} WARNING - IndexError: list index out of range
[2024-09-29T09:05:15.233+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-09-29T09:05:15.260+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flats, task_id=get_flats, execution_date=20240929T085609, start_date=20240929T085717, end_date=20240929T090515
[2024-09-29T09:05:15.367+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-29T09:05:15.423+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
