[2024-09-29T08:00:28.880+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T07:58:37.633706+00:00 [queued]>
[2024-09-29T08:00:28.915+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T07:58:37.633706+00:00 [queued]>
[2024-09-29T08:00:28.917+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T08:00:28.954+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_flats> on 2024-09-29 07:58:37.633706+00:00
[2024-09-29T08:00:28.974+0000] {standard_task_runner.py:57} INFO - Started process 7273 to run task
[2024-09-29T08:00:28.982+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_flats', 'manual__2024-09-29T07:58:37.633706+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpwdl4b_u8']
[2024-09-29T08:00:28.990+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask get_flats
[2024-09-29T08:00:29.162+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_flats manual__2024-09-29T07:58:37.633706+00:00 [running]> on host 5096eb060c49
[2024-09-29T08:00:29.668+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_flats' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T07:58:37.633706+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T07:58:37.633706+00:00'
[2024-09-29T08:00:29.794+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-1:
[2024-09-29T08:00:29.795+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.796+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.800+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.802+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.804+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.808+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.813+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.815+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.823+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-2:
[2024-09-29T08:00:29.824+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.825+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.827+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.828+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.830+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.831+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.833+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.833+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.836+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-3:
[2024-09-29T08:00:29.838+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.840+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.841+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.842+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.843+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.844+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.846+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.848+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.850+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-4:
[2024-09-29T08:00:29.853+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.853+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.856+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.858+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.861+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.863+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.865+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.866+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.869+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-5:
[2024-09-29T08:00:29.870+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.870+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.871+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.872+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.874+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.874+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.876+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.878+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.879+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-6:
[2024-09-29T08:00:29.880+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.880+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.882+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.883+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.884+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.884+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.886+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.888+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.890+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-7:
[2024-09-29T08:00:29.892+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.893+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.894+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.896+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.899+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.900+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.902+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.902+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.904+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-8:
[2024-09-29T08:00:29.905+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.905+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.907+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.908+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.909+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.910+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.912+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.912+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.913+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-9:
[2024-09-29T08:00:29.914+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.914+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.915+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.916+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.918+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.918+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.919+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.919+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.922+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-10:
[2024-09-29T08:00:29.924+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.925+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.926+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.927+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.930+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.932+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.934+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.935+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.937+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-11:
[2024-09-29T08:00:29.939+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.939+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.941+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.942+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.943+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.944+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.946+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.947+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.949+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-12:
[2024-09-29T08:00:29.951+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.951+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.953+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.955+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.957+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.958+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.961+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.962+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.964+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-13:
[2024-09-29T08:00:29.964+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.966+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.967+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.968+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.970+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.971+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.973+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.974+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.975+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-14:
[2024-09-29T08:00:29.976+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.977+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.978+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.979+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:29.980+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:29.980+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:29.983+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:29.984+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:29.985+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-15:
[2024-09-29T08:00:29.988+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:29.992+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:29.995+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:29.999+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.001+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.003+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.009+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.011+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.012+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-16:
[2024-09-29T08:00:30.013+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.016+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.019+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.022+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.025+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.026+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.028+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.029+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.030+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-17:
[2024-09-29T08:00:30.031+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.032+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.033+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.034+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.035+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.035+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.039+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.039+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.044+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-18:
[2024-09-29T08:00:30.044+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.045+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.045+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.047+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.050+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.051+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.061+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.062+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.063+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-19:
[2024-09-29T08:00:30.065+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.068+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.069+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.072+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.074+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.076+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.079+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.080+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.083+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-20:
[2024-09-29T08:00:30.091+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.094+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.095+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.097+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.100+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.100+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.101+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.102+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.103+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-21:
[2024-09-29T08:00:30.103+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.104+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.105+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.105+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.108+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.108+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.109+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.110+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.111+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-22:
[2024-09-29T08:00:30.112+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.113+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.115+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.116+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.118+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.119+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.120+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.127+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.131+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-23:
[2024-09-29T08:00:30.132+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.134+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.135+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.139+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.143+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.144+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.151+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.156+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.159+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-24:
[2024-09-29T08:00:30.160+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.160+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.161+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.161+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.163+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.163+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.166+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.167+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.169+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-25:
[2024-09-29T08:00:30.171+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.172+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.175+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.177+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.178+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.179+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.181+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.182+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.185+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-26:
[2024-09-29T08:00:30.187+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.188+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.190+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.192+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.194+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.195+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.196+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.196+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.198+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-27:
[2024-09-29T08:00:30.200+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.200+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.201+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.202+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.204+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.204+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.206+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.207+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.208+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-28:
[2024-09-29T08:00:30.210+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.210+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.211+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.212+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.213+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.213+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.220+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.221+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.222+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-29:
[2024-09-29T08:00:30.224+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.225+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.226+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.226+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.227+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.228+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.230+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.230+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.232+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-30:
[2024-09-29T08:00:30.232+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:00:30.233+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:00:30.233+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:00:30.234+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:00:30.235+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:00:30.235+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T08:00:30.236+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T08:00:30.237+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T08:00:30.238+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-09-29T08:00:30.268+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flats, task_id=get_flats, execution_date=20240929T075837, start_date=20240929T080028, end_date=20240929T080030
[2024-09-29T08:00:30.444+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-29T08:00:30.613+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
