[2024-09-29T08:56:18.848+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.clear_data manual__2024-09-29T08:56:09.532251+00:00 [queued]>
[2024-09-29T08:56:18.871+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.clear_data manual__2024-09-29T08:56:09.532251+00:00 [queued]>
[2024-09-29T08:56:18.872+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T08:56:18.903+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): clear_data> on 2024-09-29 08:56:09.532251+00:00
[2024-09-29T08:56:18.932+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2024-09-29T08:56:19.011+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'clear_data', 'manual__2024-09-29T08:56:09.532251+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmp3oq9as4g']
[2024-09-29T08:56:19.033+0000] {standard_task_runner.py:85} INFO - Job 209: Subtask clear_data
[2024-09-29T08:56:19.406+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.clear_data manual__2024-09-29T08:56:09.532251+00:00 [running]> on host 5096eb060c49
[2024-09-29T08:56:19.837+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='clear_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T08:56:09.532251+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T08:56:09.532251+00:00'
[2024-09-29T08:56:19.845+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-09-29T08:56:19.868+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flats, task_id=clear_data, execution_date=20240929T085609, start_date=20240929T085618, end_date=20240929T085619
[2024-09-29T08:56:19.929+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-29T08:56:19.978+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: flats.get_coords manual__2024-09-29T08:56:09.532251+00:00 [None]>. Marking it as removed.
[2024-09-29T08:56:19.989+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: flats.transform_to_dims manual__2024-09-29T08:56:09.532251+00:00 [None]>. Marking it as removed.
[2024-09-29T08:56:19.992+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: flats.transform_to_facts manual__2024-09-29T08:56:09.532251+00:00 [None]>. Marking it as removed.
[2024-09-29T08:56:19.997+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: flats.create_dims manual__2024-09-29T08:56:09.532251+00:00 [None]>. Marking it as removed.
[2024-09-29T08:56:20.002+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: flats.create_facts manual__2024-09-29T08:56:09.532251+00:00 [None]>. Marking it as removed.
[2024-09-29T08:56:20.026+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
